# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Filling Space So This Nav Div Has Overflow Y
  items:
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq
    - label: FAQ
      link: /faq

    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
- label: Usage
  items:
    - label: "Creating docs"
      link: "/usage/creating-docs"
    - label: "Navigation"
      link: "/usage/navigation"
    - label: "Shadowing"
      link: "/usage/shadowing"



